language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=queued_storage.test_settings
  - export CELERY_CONFIG_MODULE=queued_storage.tests.celeryconfig
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7.7
    - python: 2.6
      env: DJANGO=1.8     